### ISSUE TITLE
Обеспечьте строгую гарантию оператора = 

### ISSUE THREAD

**Issue by simplydesigner** [yar-yasenkov/stack#6]
https://github.com/yar-yasenkov/stack/blob/ef317be1358f40a2b848e300871d0fe973d810c4/include/Stack.h#L55-L66

**Comment by yar-yasenkov** [comment]
теперь при вызове исключения в new_copy  поля объекта остаются в неиспорченном состоянии
https://github.com/yar-yasenkov/stack/commit/99afc84e8ad21cd525f537b073ea3d20f4870fdd
